-- programmers - 상품을 구매한 회원 비율 구하기
-- set, between, round

SET @TOTAL := 0;
SELECT COUNT(*)
INTO @TOTAL
FROM USER_INFO
WHERE JOINED BETWEEN '2021-01-01' AND '2022-01-01';

SELECT YEAR, MONTH, COUNT(*) AS PUCHASED_USERS, ROUND((COUNT(*) / @TOTAL), 1) AS PUCHASED_RATIO
FROM (SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID
                    FROM USER_INFO
                    WHERE JOINED BETWEEN '2021-01-01' AND '2022-01-01')
    GROUP BY USER_ID, MONTH(SALES_DATE)) AS A
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;