-- programmers - 자동차 대여 기록 별 대여 금액 구하기
-- round, if, datediff, join(inner join), replace

SELECT HISTORY_ID, ROUND((100 - IF(DISCOUNT_RATE IS NULL, 0, DISCOUNT_RATE)) * DAILY_FEE * DAYS / 100, 0) AS FEE
FROM (SELECT H.HISTORY_ID, C.DAILY_FEE,
            DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DAYS,
            (SELECT MAX(DISCOUNT_RATE)
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
            WHERE CAR_TYPE = '트럭'
            AND REPLACE(DURATION_TYPE, '일 이상', '') <= DATEDIFF(H.END_DATE, H.START_DATE)+1) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭') H
ORDER BY FEE DESC, HISTORY_ID DESC