-- programmers - 조건에 부합하는 중고거래 댓글 조회하기
-- date_format(datetime, '%Y-%m-%d')

SELECT A.TITLE, B.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD A RIGHT JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID
WHERE YEAR(A.CREATED_DATE) = '2022' AND MONTH(A.CREATED_DATE) = '10'
ORDER BY B.CREATED_DATE, A.TITLE