-- programmers - 즐겨찾기가 가장 많은 식당 정보 출력하기
-- group by

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO A
WHERE FAVORITES = (SELECT MAX(FAVORITES)
                FROM REST_INFO B
                WHERE A.FOOD_TYPE = B.FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC