-- programmers - 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
-- join, cast, like, between, not in

SELECT *
FROM (SELECT CAR_ID, C.CAR_TYPE, CAST(DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30 AS SIGNED) AS FEE
    FROM (SELECT CAR_TYPE, DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE LIKE '30%') AS C
    JOIN (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
            FROM CAR_RENTAL_COMPANY_CAR A
            WHERE (A.CAR_TYPE = 'SUV' OR A.CAR_TYPE = '세단')
            AND A.CAR_ID NOT IN (SELECT CAR_ID
                                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                WHERE END_DATE > '2022-11-01')) AS A
    ON C.CAR_TYPE = A.CAR_TYPE) AS RESULT
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC